
-- Add comprehensive employee fields
ALTER TABLE public.employees
ADD COLUMN IF NOT EXISTS position_desired text,
ADD COLUMN IF NOT EXISTS application_date date DEFAULT CURRENT_DATE,
ADD COLUMN IF NOT EXISTS sex text,
ADD COLUMN IF NOT EXISTS city_address text,
ADD COLUMN IF NOT EXISTS provincial_address text,
ADD COLUMN IF NOT EXISTS telephone text,
ADD COLUMN IF NOT EXISTS date_of_birth date,
ADD COLUMN IF NOT EXISTS age integer,
ADD COLUMN IF NOT EXISTS civil_status text,
ADD COLUMN IF NOT EXISTS citizenship text,
ADD COLUMN IF NOT EXISTS height text,
ADD COLUMN IF NOT EXISTS weight text,
ADD COLUMN IF NOT EXISTS religion text,
ADD COLUMN IF NOT EXISTS spouse_name text,
ADD COLUMN IF NOT EXISTS spouse_occupation text,
ADD COLUMN IF NOT EXISTS children jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS father_name text,
ADD COLUMN IF NOT EXISTS mother_name text,
ADD COLUMN IF NOT EXISTS parents_occupation text,
ADD COLUMN IF NOT EXISTS parents_address text,
ADD COLUMN IF NOT EXISTS languages text,
ADD COLUMN IF NOT EXISTS emergency_contact_name text,
ADD COLUMN IF NOT EXISTS emergency_contact_address text,
ADD COLUMN IF NOT EXISTS emergency_contact_phone text,
ADD COLUMN IF NOT EXISTS elementary_school text,
ADD COLUMN IF NOT EXISTS elementary_year text,
ADD COLUMN IF NOT EXISTS highschool_school text,
ADD COLUMN IF NOT EXISTS highschool_year text,
ADD COLUMN IF NOT EXISTS college_school text,
ADD COLUMN IF NOT EXISTS college_year text,
ADD COLUMN IF NOT EXISTS degree_received text,
ADD COLUMN IF NOT EXISTS special_skills text,
ADD COLUMN IF NOT EXISTS employment_records jsonb DEFAULT '[]'::jsonb;
